version: '3.7'

volumes:
    postgres_data:


services:
    api:
        build: ./backend
        command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
        environment:
            DATABASE_URL: postgresql://postgres:postgres@db:5432/shorturl
        volumes:
            - ./backend:/backend
        ports:
            - 8100:8000
        depends_on:
            - db

    db:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=shorturl
        expose:
            - 5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/:cached
